services:
  mongos:
    image: mongo:8.2
    container_name: mongos-router
    command: ["mongos", "--configdb", "cfg/mongo-config:27019", "--bind_ip_all"]
    ports:
      - "27017:27017"
    depends_on:
      - mongo-config
    networks:
      - database-network
    restart: always

  mongo-config:
    image: mongo:8.2
    container_name: mongo-config
    command: ["mongod", "--configsvr", "--replSet", "cfg", "--bind_ip_all"]
    volumes:
      - 'mongo-config_data:/data/db'
    networks:
      - database-network
    restart: always

  mongo-primary:
    image: mongo:8.2
    container_name: mongo-primary
    networks:
      - database-network
    restart: always
    command: ["mongod", "--shardsvr", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - 'mongo-primary_data:/data/db'

  mongo-secondary:
    image: mongo:8.2
    container_name: mongo-secondary
    networks:
      - database-network
    restart: always
    command: ["mongod", "--shardsvr", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - 'mongo-secondary_data:/data/db'

  mongo-tertiary:
    image: mongo:8.2
    container_name: mongo-tertiary
    networks:
      - database-network
    restart: always
    command: ["mongod", "--shardsvr", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - 'mongo-tertiary_data:/data/db'

  mongo-shard2:
    image: mongo:8.2
    container_name: mongo-shard2
    restart: always
    command: ["mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all"]
    volumes:
      - 'mongo-shard2_data:/data/db'
    networks:
      - database-network

  mongo-shard3:
    image: mongo:8.2
    container_name: mongo-shard3
    restart: always
    command: ["mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all"]
    volumes:
      - 'mongo-shard3_data:/data/db'
    networks:
      - database-network

  compass-web:
    image: haohanyang/compass-web
    container_name: compass-web
    networks:
      - database-network
    ports:
      - "8081:8080"
    command: ["compass-web", "--host", "0.0.0.0", "--mongo-uri", "mongodb://mongos:27017"]
    depends_on:
      - mongos
    restart: always

  cluster-setup:
    image: mongo:8.2
    container_name: cluster-setup
    depends_on:
      - mongo-config
      - mongo-primary
    networks:
      - database-network
    entrypoint: >
      bash -c "
        echo '1. Inicializace Config serveru (PORT 27019)...' &&
        until mongosh --host mongo-config --port 27019 --eval 'rs.initiate({_id: \"cfg\", configsvr: true, members: [{_id: 0, host: \"mongo-config:27019\"}]})' 2>/dev/null; do
          sleep 2;
        done &&
      
        echo '2. Inicializace Shardů (PORT 27018)...' &&
        # ČEKÁNÍ NA PRIMARY SHARD - PORT 27018
        until mongosh --host mongo-primary --port 27018 --eval 'db.runCommand({ping:1})' &>/dev/null; do
          echo 'Čekám na uzel mongo-primary na portu 27018...'; sleep 2;
        done &&
      
        mongosh --host mongo-primary --port 27018 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo-primary:27018\"}, {_id: 1, host: \"mongo-secondary:27018\"}, {_id: 2, host: \"mongo-tertiary:27018\"}]})' &&
      
        # SHARD 2 - PORT 27018
        until mongosh --host mongo-shard2 --port 27018 --eval 'db.runCommand({ping:1})' &>/dev/null; do
          sleep 2;
        done &&
        mongosh --host mongo-shard2 --port 27018 --eval 'rs.initiate({_id: \"rs1\", members: [{_id: 0, host: \"mongo-shard2:27018\"}]})' &&
      
        # SHARD 3 - PORT 27018
        until mongosh --host mongo-shard3 --port 27018 --eval 'db.runCommand({ping:1})' &>/dev/null; do
          sleep 2;
        done &&
        mongosh --host mongo-shard3 --port 27018 --eval 'rs.initiate({_id: \"rs2\", members: [{_id: 0, host: \"mongo-shard3:27018\"}]})' &&
      
        echo 'Čekám 30s na stabilizaci...' &&
        sleep 30 &&
      
        echo '3. Propojení přes Router (Mmongos zůstává na 27017)...' &&
        until mongosh --host mongos --port 27017 --eval 'db.runCommand({ping:1})' &>/dev/null; do
          sleep 2;
        done &&
      
        mongosh --host mongos --port 27017 --eval '
          sh.addShard(\"rs0/mongo-primary:27018,mongo-secondary:27018,mongo-tertiary:27018\");
          sh.addShard(\"rs1/mongo-shard2:27018\");
          sh.addShard(\"rs2/mongo-shard3:27018\");
        ' &&
        echo 'HOTOVO! Cluster je kompletní.'
      "

networks:
  database-network:

volumes:
  mongo-config_data:
  mongo-primary_data:
  mongo-secondary_data:
  mongo-tertiary_data:
  mongo-shard2_data:
  mongo-shard3_data: