services:

  keyfile-init:
    image: mongo:8.2
    container_name: keyfile-init
    volumes:
      - mongo-keyfile:/etc/mongo
    entrypoint: >
      bash -c "
        if [ ! -f /etc/mongo/mongo.key ]; then
          openssl rand -base64 756 > /etc/mongo/mongo.key &&
          chmod 400 /etc/mongo/mongo.key &&
          chown 999:999 /etc/mongo/mongo.key &&
          echo 'Keyfile generated.';
        else
          echo 'Keyfile already exist, skipping.';
        fi
      "
    networks:
      - database-network

  mongo-config:
    image: mongo:8.2
    container_name: mongo-config
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--configsvr", "--replSet", "cfg", "--bind_ip_all", "--port", "27019" ]
    environment:
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      RS_INITIATE: '{"_id":"cfg","configsvr":true,"members":[{"_id":0,"host":"mongo-config:27019"}, {"_id":1,"host":"mongo-config-2:27019"}, {"_id":2,"host":"mongo-config-3:27019"}]}'
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-config_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongo-config-2:
    image: mongo:8.2
    container_name: mongo-config-2
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--configsvr", "--replSet", "cfg", "--bind_ip_all", "--port", "27019" ]
    environment:
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-config_data_2:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always
  mongo-config-3:
    image: mongo:8.2
    container_name: mongo-config-3
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--configsvr", "--replSet", "cfg", "--bind_ip_all", "--port", "27019" ]
    environment:
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-config_data_3:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongo-primary:
    image: mongo:8.2
    container_name: mongo-primary
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs0", "--bind_ip_all" ]
    environment:
      RS_INITIATE: '{"_id":"rs0","members":[{"_id":0,"host":"mongo-primary:27018"},{"_id":1,"host":"mongo-secondary:27018"},{"_id":2,"host":"mongo-tertiary:27018"}]}'
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-primary_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongo-secondary:
    image: mongo:8.2
    container_name: mongo-secondary
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs0", "--bind_ip_all" ]
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-secondary_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongo-tertiary:
    image: mongo:8.2
    container_name: mongo-tertiary
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs0", "--bind_ip_all" ]
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-tertiary_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongo-shard2:
    image: mongo:8.2
    container_name: mongo-shard2
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all" ]
    environment:
      RS_INITIATE: '{"_id":"rs1","members":[{"_id":0,"host":"mongo-shard2:27018"}, {"_id":1,"host":"mongo-shard2b:27018"}, {"_id":2,"host":"mongo-shard2c:27018"}]}'
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-shard2_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always
  mongo-shard2b:
    image: mongo:8.2
    container_name: mongo-shard2b
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all" ]
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-shard2b_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always
  mongo-shard2c:
    image: mongo:8.2
    container_name: mongo-shard2c
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all" ]
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-shard2c_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongo-shard3:
    image: mongo:8.2
    container_name: mongo-shard3
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all" ]
    environment:
      RS_INITIATE: '{"_id":"rs2","members":[{"_id":0,"host":"mongo-shard3:27018"}, {"_id":1,"host":"mongo-shard3b:27018"}, {"_id":2,"host":"mongo-shard3c:27018"}]}'
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-shard3_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always
  mongo-shard3b:
    image: mongo:8.2
    container_name: mongo-shard3b
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all" ]
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-shard3b_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always
  mongo-shard3c:
    image: mongo:8.2
    container_name: mongo-shard3c
    entrypoint: [ "/scripts/mongo-init.sh" ]
    command: [ "mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all" ]
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
    volumes:
      - mongo-shard3c_data:/data/db
      - mongo-keyfile:/etc/mongo:ro
      - ./mongo-init.sh:/scripts/mongo-init.sh:ro
    networks:
      - database-network
    restart: always

  mongos:
    image: mongo:8.2
    container_name: mongos-router
    command: [ "mongos", "--configdb", "cfg/mongo-config:27019,mongo-config-2:27019,mongo-config-3:27019", "--bind_ip_all",
               "--keyFile", "/etc/mongo/mongo.key" ]
    ports:
      - "27017:27017"
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
      mongo-config:
        condition: service_started
    volumes:
      - mongo-keyfile:/etc/mongo:ro
    networks:
      - database-network
    restart: always

  mongos2:
    image: mongo:8.2
    container_name: mongos-router-2
    command: [ "mongos", "--configdb", "cfg/mongo-config:27019,mongo-config-2:27019,mongo-config-3:27019", "--bind_ip_all",
               "--keyFile", "/etc/mongo/mongo.key" ]
    ports:
      - "27020:27017"
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
      mongo-config:
        condition: service_started
    volumes:
      - mongo-keyfile:/etc/mongo:ro
    networks:
      - database-network
    restart: always
  mongos3:
    image: mongo:8.2
    container_name: mongos-router-3
    command: [ "mongos", "--configdb", "cfg/mongo-config:27019,mongo-config-2:27019,mongo-config-3:27019", "--bind_ip_all",
               "--keyFile", "/etc/mongo/mongo.key" ]
    ports:
      - "27021:27017"
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
      mongo-config:
        condition: service_started
    volumes:
      - mongo-keyfile:/etc/mongo:ro
    networks:
      - database-network
    restart: always

  compass-web:
    image: haohanyang/compass-web
    container_name: compass-web
    ports:
      - "8081:8080"
    command: [ "compass-web", "--host", "0.0.0.0", "--mongo-uri",
               "mongodb://admin:${MONGO_ADMIN_PASSWORD}@mongos:27017,mongos2:27017,mongos3:27017/?authSource=admin" ]
    depends_on:
      - mongos
    networks:
      - database-network
    restart: always

  cluster-setup:
    image: mongo:8.2
    container_name: cluster-setup
    depends_on:
      mongo-config:
        condition: service_started
      mongo-primary:
        condition: service_started
      mongos:
        condition: service_started
    networks:
      - database-network
    volumes:
      - ./:/setup_data:ro
      - ../Data:/json_data:ro
    environment:
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_REPORTER_PASSWORD: ${MONGO_REPORTER_PASSWORD}
    entrypoint: >
      bash -c "
        echo '1. Waiting for Config server...' &&
        until mongosh --quiet --host mongo-config --port 27019 --eval 'db.hello().isWritablePrimary' | grep -q 'true'; do
          sleep 2;
        done &&
      
        echo '2. Waiting for rs0 (Primary)...' &&
        until mongosh --quiet --host mongo-primary --port 27018 --eval 'db.hello().isWritablePrimary' | grep -q 'true'; do
          sleep 2;
        done &&
      
        echo '3. Waiting for (Shard 2)...' &&
        until mongosh --quiet --host mongo-shard2 --port 27018 --eval 'db.hello().isWritablePrimary' | grep -q 'true'; do
          sleep 2;
        done &&
      
        echo '4. Waiting for (Shard 3)...' &&
        until mongosh --quiet --host mongo-shard3 --port 27018 --eval 'db.hello().isWritablePrimary' | grep -q 'true'; do
          sleep 2;
        done &&
      
        echo '5. Waiting for mongos (Router)...' &&
        until mongosh --quiet --host mongos --port 27017 --eval 'db.adminCommand({ping:1}).ok' | grep -q '1'; do
          sleep 2;
        done &&
      
        echo '6. Adding shards to cluster...' &&
        mongosh --quiet --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin --eval '
          sh.addShard(\"rs0/mongo-primary:27018,mongo-secondary:27018,mongo-tertiary:27018\");
          sh.addShard(\"rs1/mongo-shard2:27018,mongo-shard2b:27018,mongo-shard2c:27018\");
          sh.addShard(\"rs2/mongo-shard3:27018,mongo-shard3b:27018,mongo-shard3c:27018\");
        ' &&
      
        echo '7. Running init.js (Validation and Sharding)...' &&
        mongosh --quiet --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin /setup_data/init.js &&
      
        echo '8. Import JSON data (Mongoimport)...' &&
        mongoimport --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin -d nfl_db -c games --file /json_data/games.json --type json &&
        mongoimport --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin -d nfl_db -c teams --file /json_data/teams.json --type json &&
        mongoimport --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin -d nfl_db -c rosters --file /json_data/rosters.json --type json &&
        mongoimport --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin -d nfl_db -c player_stats --file /json_data/player_stats.json --type json &&
        mongoimport --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin -d nfl_db -c plays --file /json_data/plays.json --type json &&
      
        echo '9. Creating app users...' &&
        mongosh --quiet --host mongos --port 27017 -u admin -p $MONGO_ADMIN_PASSWORD --authenticationDatabase admin --eval '
          use nfl_db;
          db.createUser({ user: \"appuser\", pwd: \"'\"'\"'$MONGO_APP_PASSWORD'\"'\"'\", roles: [{ role: \"readWrite\", db: \"nfl_db\" }] });
          db.createUser({ user: \"reporter\", pwd: \"'\"'\"'$MONGO_REPORTER_PASSWORD'\"'\"'\", roles: [{ role: \"read\", db: \"nfl_db\" }] });
        ' &&
        echo '===== DONE! CLUSTER IS READY ====='
      "

networks:
  database-network:

volumes:
  mongo-keyfile:
  mongo-config_data:
  mongo-config_data_2:
  mongo-config_data_3:
  mongo-primary_data:
  mongo-secondary_data:
  mongo-tertiary_data:
  mongo-shard2_data:
  mongo-shard2b_data:
  mongo-shard2c_data:
  mongo-shard3_data:
  mongo-shard3b_data:
  mongo-shard3c_data: